### ISSUE TITLE
incorrect module name for EUnit tests

### ISSUE THREAD

**Issue by leoliu** [schlagert/syslog#8]
Thanks for the clean application.

EUnit runs `MOD_tests.erl` automatically i.e. test module names should end with `_tests` instead of `_test`.

**Comment by schlagert** [comment]
Hi,

thank you for looking over the project, more eyes catch more bugs.

I know the `_tests.erl` naming scheme is the best practice. I got used to the false naming scheme back in the days when I was using the `maven-erlang-plugin` and just stick with it out of (bad) habit.

My question however is, does the current naming cause any troubles for you because at least my versions of rebar2 and rebar3 do run the unit tests without problems (automatically).

**Comment by schlagert** [comment]
Another good thing this issue discovered:
I just checked the (Travis CI)[https://travis-ci.org/] builds of all my projects and found the majority of them _broken_ because I had to use `rebar.config.script` files to support both rebar2 and rebar3. This unfortunately triggers Travis CI to use `make test` as build script :grin:

**Comment by leoliu** [comment]
The inconvenience is testing a single module doesn't work properly. Many IDE/editors let you test a single module. for example if I have private tests in module `m` and public tests in `m_tests`, all of them will be picked up when `eunit:test/2` on `m`.

**Comment by schlagert** [comment]
Ok, I see. I'm going to rename the test modules.

**Comment by leoliu** [comment]
Thank you.
